contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "https://timw.co/notes/"
paginate = 10
title = "Tim Whitacre | Notes"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Hacker, Educator, Whisky Drinker"
  author = "Tim Whitacre"